version: '3'

services:
  api:
    image: book-rental-api
    ports:
      - "3000:3000" # Expose port 8080
    environment:
      - dbHost=mysql
      - dbUser=root
      - dbPassword=root
      - dbName=mydb

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
